### ISSUE TITLE
Refactor the secret tokens

### ISSUE THREAD

**Issue by Officer-R** [thomasjacob04/Vader#1]
Hi @thomasjacob04 It is very exciting to see you build a simple web app with the help of LLM models.

But I need you to make sure that no one misuses your access keys since you have used them directly on the code.

https://github.com/thomasjacob04/Vader/blob/main/script.js#L2-L3

Please use an environment variable.

**Comment by thomasjacob04** [comment]
Thanks for point this out! it seems like a very basic mistake, I'm learning.. thanks

**Comment by thomasjacob04** [comment]
created separate .env file and handled it using api.php
