### ISSUE TITLE
add overflow hidden for scroll issue on body

### ISSUE THREAD

**Issue by Officer-R** [thomasjacob04/Vader#2]
Please add `overflow: hidden;` to the `<body>` element on css file for resolving the vertical scroll of the whole page and test it on your system locally and then push the code.

![Screenshot from 2024-12-09 14-46-09](https://github.com/user-attachments/assets/258f9a6a-2c3b-4a8f-8480-16b9ea4c44eb)

**Comment by thomasjacob04** [comment]
doing!

**Comment by thomasjacob04** [comment]
done.
